### ISSUE TITLE
get_datasets() lapply error

### ISSUE THREAD

**Issue by alicewolfle** [ropensci/rdhs#141]
Hi, 

I wrote this code a few months ago, and it was working well. I have tried to re-run it today, but I now get an error. I have updated the version of rdhs I am using and tried to re-run, but still same error (see below). Thanks in advance !

```r

survs <- dhs_surveys(countryIds = c("BD"),
                     surveyType = "DHS",
                     surveyYearStart = 1993)

datasets <- dhs_datasets(surveyIds = survs$SurveyId, 
                         fileFormat = "flat", 
                         fileType = "KR")

#downlaod datasets
downloads <- get_datasets(datasets$FileName)

```
The output I get from this code is: 

Logging into DHS website...
Writing your configuration to:
   -> C:/Users/........

Error in lapply(rm_between_quote(text.var, left), Trim)[[1]] : 
  subscript out of bounds

```r
> devtools::session_info() 
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                            
 version  R version 4.2.0 (2022-04-22 ucrt)
 os       Windows 10 x64                   
 system   x86_64, mingw32                  
 ui       RStudio                          
 language (EN)                             
 collate  English_United Kingdom.utf8      
 ctype    English_United Kingdom.utf8      
 tz       Europe/London                    
 date     2022-09-21    
```

**Comment by jeffeaton** [comment]
Hello,

Thanks for this. This error is not familiar to me.

Can you please post the full output of utils::sessionInfo() so that we can confirm what version of rdhs and other dependency packages are giving the error?

Thanks,
Jeff

From: alicewolfle ***@***.***>
Date: Wednesday, 21 September 2022 at 12:17
To: ropensci/rdhs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ropensci/rdhs] get_datasets() lapply error (Issue #141)

Hi,

I wrote this code a few months ago, and it was working well. I have tried to re-run it today, but I now get an error. I have updated the version of rdhs I am using and tried to re-run, but still same error (see below). Thanks in advance !

survs <- dhs_surveys(countryIds = c("BD"),



                     surveyType = "DHS",



                     surveyYearStart = 1993)







datasets <- dhs_datasets(surveyIds = survs$SurveyId,



                         fileFormat = "flat",



                         fileType = "KR")







#downlaod datasets



downloads <- get_datasets(datasets$FileName)



The output I get from this code is:

Logging into DHS website...
Writing your configuration to:
-> C:/Users/........

Error in lapply(rm_between_quote(text.var, left), Trim)[[1]] :
subscript out of bounds

> devtools::session_info()



─ Session info ───────────────────────────────────────────────────────────────────────



 setting  value



 version  R version 4.2.0 (2022-04-22 ucrt)



 os       Windows 10 x64



 system   x86_64, mingw32



 ui       RStudio



 language (EN)



 collate  English_United Kingdom.utf8



 ctype    English_United Kingdom.utf8



 tz       Europe/London



 date     2022-09-21
