### ISSUE TITLE
Add shape files to download options

### ISSUE THREAD

**Issue by OJWatson** [ropensci/rdhs#71]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

Be able to query and download from https://spatialdata.dhsprogram.com/home/ as well.

**Comment by OJWatson** [comment]
Also  would be a useful tool to harmoise regions between surveys in which admins change, i.e. decide on which regions you want throughout and then produce admin estimates for those regions with the correct shape

**Comment by Guerillero** [comment]
If there is something on the data end that we can do to make this easier, please let me know!

**Comment by OJWatson** [comment]
Hey, I think it will actually not be too bad I just struggling with time my end. Thank you though

**Comment by jeffeaton** [comment]
Hi @Guerillero,

Since you asked...it would be helpful to be able to easily merge the area boundaries to the survey datasets. 

Most of the boundaries are available via the geometry API endpoint (already accessible to R via `dhs_geometry()`). I think this API endpoint is likely to be preferable to web scraping download the boundary files from https://spatialdata.dhsprogram.com.

Would it be possible to add the be to add the `DHSREGCO`/`REGCODE` variable and ideally the `REGVAR` from the shapefile datasets to the `geometry` API endpoint?

Thanks,
Jeff

**Comment by OJWatson** [comment]
Fixed in #95
